# Estrategia de generación de tablas
quarkus.hibernate-orm.database.generation=drop-and-create
# Mostrar SQL en consola 
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.format-sql=true
# Forzar el uso de PostgreSQL
quarkus.datasource.db-kind=postgresql
# Esto crea la tabla cada vez que inicias (para evitar el error de "Table not found")
quarkus.hibernate-orm.database.generation=drop-and-createtgtfrdeswdefrtghyjukm,l.ñ-{cccccc vvv}