# Estrategia de generación: Borra y recrea las tablas (ideal para desarrollo)
quarkus.hibernate-orm.database.generation=drop-and-create
# Visualización de SQL con formato profesional
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.format-sql=true
# Motor de Base de Datos: PostgreSQL (Activa Dev Services con Docker)
quarkus.datasource.db-kind=postgresql
